name: lane_detection_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.6.9
  - numpy
  - matplotlib
  - jupyter
  - pillow
  - scikit-learn
  - scikit-image
  - scipy
  - h5py
  - eventlet
  - flask-socketio
  - seaborn
  - pandas
  - imageio
  - opencv
  - pip:
      - moviepy
      - requests
      - docopt
      - glob3
